#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogger.Mvc.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
    using EventLogger.Enums;
    
    #line default
    #line hidden
    using EventLogger.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LoggerMainLayout.cshtml")]
    public partial class _LoggerMainLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _LoggerMainLayout()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
   
    var controller = ViewContext.RouteData.Values["Controller"].ToString().ToLower();
    var action = ViewContext.RouteData.Values["action"].ToString().ToLower();
    var eventLogTypeValue = Request.QueryString["eventLogType"];
    var eventLogType ="error";
    if (eventLogTypeValue != null)
    {
        eventLogType = eventLogTypeValue.ToString().ToLower();
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>EventLogger: ");

            
            #line 18 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n");

WriteLiteral("    ");

            
            #line 19 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
Write(Styles.Render("~/Content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
Write(Scripts.Render("~/bundles/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
           Write(Html.ActionLink("EventLogger", "Index", "EventLogs", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1563), Tuple.Create("\"", 1667)
, Tuple.Create(Tuple.Create("", 1571), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 36 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                if(action=="index" && controller=="eventlogs" && eventLogType=="error") {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, " ");

WriteLiteralTo(__razor_attribute_value_writer, "active");

            
            #line 36 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                                                                                                             }
            
            #line default
            #line hidden
}), 1571), false)
, Tuple.Create(Tuple.Create(" ", 1666), Tuple.Create("", 1666), true)
);

WriteLiteral(">");

            
            #line 36 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                                                                                                            Write(Html.ActionLink("Errors List", "Index", "EventLogs", new { eventLogType = EventLogType.Error }, new { }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li");

WriteAttribute("class", Tuple.Create(" class=\"", 1804), Tuple.Create("\"", 1908)
, Tuple.Create(Tuple.Create("", 1812), Tuple.Create<System.Object, System.Int32>(new System.Web.WebPages.HelperResult(__razor_attribute_value_writer => {

            
            #line 37 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                if(action=="index" && controller=="eventlogs" && eventLogType=="event") {
            
            #line default
            #line hidden
WriteLiteralTo(__razor_attribute_value_writer, " ");

WriteLiteralTo(__razor_attribute_value_writer, "active");

            
            #line 37 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                                                                                                             }
            
            #line default
            #line hidden
}), 1812), false)
, Tuple.Create(Tuple.Create(" ", 1907), Tuple.Create("", 1907), true)
);

WriteLiteral(">");

            
            #line 37 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
                                                                                                                            Write(Html.ActionLink("Events List", "Index", "EventLogs", new { eventLogType= EventLogType.Event },new { }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n    </div>\r\n   " +
" <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 43 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n        <footer>\r\n            <p>\r\n                powered by <" +
"a");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" href=\"https://github.com/hamed-shirbandi/EventLogger\"");

WriteLiteral(">EventLogger</a> \r\n            </p>\r\n        </footer>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 52 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 53 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
Write(Scripts.Render("~/bundles/bootstrap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 54 "..\..\Views\Shared\_LoggerMainLayout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
