#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogger.Mvc.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventLogger.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EventLogs/Details.cshtml")]
    public partial class Details : System.Web.Mvc.WebViewPage<EventLogger.Service.EventLogs.Dto.EventLogOutput>
    {
        public Details()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\EventLogs\Details.cshtml"
  
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LoggerMainLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" style=\"margin-top:20px;\"");

WriteLiteral(">\r\n\r\n");

            
            #line 10 "..\..\Views\EventLogs\Details.cshtml"
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\EventLogs\Details.cshtml"
     if (Model.EventLogType == EventLogger.Enums.EventLogType.Error)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <h3> ");

            
            #line 13 "..\..\Views\EventLogs\Details.cshtml"
            Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral(" </h3>\r\n            <h4");

WriteLiteral(" class=\"text-primary\"");

WriteLiteral("> ");

            
            #line 14 "..\..\Views\EventLogs\Details.cshtml"
                                 Write(Model.TypeName);

            
            #line default
            #line hidden
WriteLiteral(" </h4><br />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"alert alert-warning\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\EventLogs\Details.cshtml"
           Write(Model.Details);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>Status Code :</strong>\r\n");

WriteLiteral("            ");

            
            #line 24 "..\..\Views\EventLogs\Details.cshtml"
       Write(Model.StatusCode);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>Source :</strong>\r\n            <p> ");

            
            #line 29 "..\..\Views\EventLogs\Details.cshtml"
           Write(Model.Source);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>Message :</strong>\r\n            <p> ");

            
            #line 34 "..\..\Views\EventLogs\Details.cshtml"
           Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>Inner Message :</strong>\r\n");

WriteLiteral("            ");

            
            #line 39 "..\..\Views\EventLogs\Details.cshtml"
       Write(Model.InnerMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>Help Link :</strong>\r\n");

WriteLiteral("            ");

            
            #line 44 "..\..\Views\EventLogs\Details.cshtml"
       Write(Model.HelpLink);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <hr />\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n            <strong>HResult :</strong>\r\n");

WriteLiteral("            ");

            
            #line 49 "..\..\Views\EventLogs\Details.cshtml"
       Write(Model.HResult);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <hr />\r\n        </div>\r\n");

            
            #line 52 "..\..\Views\EventLogs\Details.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Date Time :</strong>\r\n");

WriteLiteral("        ");

            
            #line 56 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.CreateDateTime);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Machine Name :</strong>\r\n");

WriteLiteral("        ");

            
            #line 61 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.MachineName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Host Name :</strong>\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.UserHostName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>IP Address :</strong>\r\n");

WriteLiteral("        ");

            
            #line 72 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Ip);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Protocol :</strong>\r\n");

WriteLiteral("        ");

            
            #line 77 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Protocol);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Http Host :</strong>\r\n");

WriteLiteral("        ");

            
            #line 82 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.HttpHost);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Port :</strong>\r\n");

WriteLiteral("        ");

            
            #line 87 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Port);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Http Method :</strong>\r\n");

WriteLiteral("        ");

            
            #line 92 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.HttpMethod);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>User :</strong>\r\n");

WriteLiteral("        ");

            
            #line 97 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>User Agent :</strong>\r\n");

WriteLiteral("        ");

            
            #line 102 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.UserAgent);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Controller :</strong>\r\n");

WriteLiteral("        ");

            
            #line 107 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Controller);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Action :</strong>\r\n");

WriteLiteral("        ");

            
            #line 112 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Action);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Route Values :</strong>\r\n");

WriteLiteral("        ");

            
            #line 117 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.RouteValues);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Url :</strong>\r\n");

WriteLiteral("        ");

            
            #line 122 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Url);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Url Referer :</strong>\r\n");

WriteLiteral("        ");

            
            #line 127 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.UrlReferer);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Path Info :</strong>\r\n");

WriteLiteral("        ");

            
            #line 132 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.PathInfo);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>QueryString :</strong>\r\n");

WriteLiteral("        ");

            
            #line 137 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.QueryString);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>UrlReferer :</strong>\r\n");

WriteLiteral("        ");

            
            #line 142 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.UrlReferer);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Physical Path :</strong>\r\n");

WriteLiteral("        ");

            
            #line 147 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.PhysicalPath);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Physical Application Path :</strong>\r\n");

WriteLiteral("        ");

            
            #line 152 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.PhysicalApplicationPath);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Form :</strong>\r\n");

WriteLiteral("        ");

            
            #line 157 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Form);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Cookies :</strong>\r\n");

WriteLiteral("        ");

            
            #line 162 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.Cookies);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"\"");

WriteLiteral(">\r\n        <strong>Server Variables :</strong>\r\n");

WriteLiteral("        ");

            
            #line 167 "..\..\Views\EventLogs\Details.cshtml"
   Write(Model.ServerVariables);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <hr />\r\n    </div>\r\n\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
