#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogger.Mvc.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using EventLogger.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EventLogs/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<EventLogger.Service.EventLogs.Dto.EventLogOutput>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\EventLogs\Index.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\EventLogs\Index.cshtml"
      
        ViewBag.Title = "Index";
    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <h2> Index </h2>\r\n");

            
            #line 9 "..\..\Views\EventLogs\Index.cshtml"
 foreach (var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <h2> Log Id =  ");

            
            #line 11 "..\..\Views\EventLogs\Index.cshtml"
              Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 12 "..\..\Views\EventLogs\Index.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
