#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventLogger.Mvc.Views
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\EventLogs\Index.cshtml"
    using EventLogger.Enums;
    
    #line default
    #line hidden
    using EventLogger.Mvc;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/EventLogs/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<EventLogger.Service.EventLogs.Dto.EventLogOutput>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\EventLogs\Index.cshtml"
  
    ViewBag.Title = "Log List";
    Layout = "~/Views/Shared/_LoggerMainLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\EventLogs\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\EventLogs\Index.cshtml"
             using (Html.BeginForm(actionName: "index", controllerName: "EventLogs", routeValues: new { }, method: FormMethod.Get, htmlAttributes: new { @class = "form-inline" }))
            {

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 13 "..\..\Views\EventLogs\Index.cshtml"
               Write(Html.TextBox("term",null,new { @class = "form-control", @placeholder = "search something" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 16 "..\..\Views\EventLogs\Index.cshtml"
               Write(Html.DropDownList("SortOrder", null, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

WriteLiteral("                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Search</button>\r\n");

            
            #line 19 "..\..\Views\EventLogs\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n        <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Views\EventLogs\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\EventLogs\Index.cshtml"
                 if (ViewBag.CurrentEventLogType == EventLogType.Error)
                {
                    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\EventLogs\Index.cshtml"
               Write(Html.Partial("_ErrorLogs", Model));

            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\EventLogs\Index.cshtml"
                                                      
                }
                else
                {
                    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\EventLogs\Index.cshtml"
               Write(Html.Partial("_EventLogs", Model));

            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\EventLogs\Index.cshtml"
                                                      
                }

            
            #line default
            #line hidden
WriteLiteral("\r\n            </table>\r\n            <div");

WriteLiteral(" style=\"\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\EventLogs\Index.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\EventLogs\Index.cshtml"
                     for (int i = 1; i <= ViewBag.PageSize; i++)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <li ");

            
            #line 37 "..\..\Views\EventLogs\Index.cshtml"
                             if (i == ViewBag.CurrentPage) {
            
            #line default
            #line hidden
WriteLiteral(" ");

WriteLiteral(" class=\"active\" ");

WriteLiteral("      ");

            
            #line 37 "..\..\Views\EventLogs\Index.cshtml"
                                                                                                }
            
            #line default
            #line hidden
WriteLiteral(">\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1612), Tuple.Create("\"", 1837)
            
            #line 38 "..\..\Views\EventLogs\Index.cshtml"
, Tuple.Create(Tuple.Create("", 1619), Tuple.Create<System.Object, System.Int32>(Url.Action(actionName:"index",controllerName: "EventLogs", routeValues:new { page=i,term= Request.QueryString["term"], sortOrder = Request.QueryString["sortOrder"], eventLogType = Request.QueryString["eventLogType"]})
            
            #line default
            #line hidden
, 1619), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 39 "..\..\Views\EventLogs\Index.cshtml"
                           Write(i);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n                        </li>\r\n");

            
            #line 42 "..\..\Views\EventLogs\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ul>\r\n            </div>\r\n");

            
            #line 45 "..\..\Views\EventLogs\Index.cshtml"
            
            
            #line default
            #line hidden
            
            #line 45 "..\..\Views\EventLogs\Index.cshtml"
             if (ViewBag.PageSize>0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div>\r\n                    page ");

            
            #line 48 "..\..\Views\EventLogs\Index.cshtml"
                    Write(ViewBag.CurrentPage);

            
            #line default
            #line hidden
WriteLiteral(" of ");

            
            #line 48 "..\..\Views\EventLogs\Index.cshtml"
                                            Write(ViewBag.PageSize);

            
            #line default
            #line hidden
WriteLiteral(" - total count is ");

            
            #line 48 "..\..\Views\EventLogs\Index.cshtml"
                                                                               Write(ViewBag.TotalItemCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");

            
            #line 50 "..\..\Views\EventLogs\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("          \r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
